package main

import (
	"fmt"
)

var (
	sceneNames = map[string]string{
		"Overworld Redux":              "Overworld",
		"Resurrection":                 "Resurrection",
		"Furnace":                      "West Furnace",
		"CubeRoom":                     "Cube Cave",
		"Sword Cave":                   "Stick House",
		"Windmill":                     "Windmill",
		"EastFiligreeCache":            "Southeast Cross Door",
		"Overworld Cave":               "Caustic Light Cave",
		"Ruins Passage":                "Ruined Passage",
		"PatrolCave":                   "Patrol Cave",
		"Waterfall":                    "Secret Gathering Place",
		"Town_FiligreeRoom":            "Fountain Cross Door",
		"Town Basement":                "Hourglass Cave",
		"Maze Room":                    "Maze Cave",
		"Ruined Shop":                  "Ruined Shop",
		"Changing Room":                "Changing Room",
		"ShopSpecial":                  "Special Shop",
		"Overworld Interiors":          "Old House",
		"Transit":                      "Far Shore",
		"Temple":                       "Sealed Temple",
		"Shop":                         "Shop",
		"Trinket Well":                 "Coins in the Well",
		"Forest Belltower":             "Forest Belltower",
		"East Forest Redux":            "East Forest",
		"Sword Access":                 "Forest Grave Path",
		"East Forest Redux Interior":   "Guardhouse 2",
		"East Forest Redux Laddercave": "Guardhouse 1",
		"Forest Boss Room":             "Forest Boss Room",
		"Sewer":                        "Beneath the Well",
		"Sewer_Boss":                   "Dark Tomb Checkpoint",
		"Crypt Redux":                  "Dark Tomb",
		"Archipelagos Redux":           "West Garden",
		"archipelagos_house":           "West Garden House",
		"Atoll Redux":                  "Ruined Atoll",
		"Frog Stairs":                  "Frog Stairway",
		"frog cave main":               "Frog's Domain",
		"Library Exterior":             "Library Exterior",
		"Library Hall":                 "Library Hall",
		"Library Rotunda":              "Library Rotunda",
		"Library Lab":                  "Library Lab",
		"Library Arena":                "Librarian",
		"Fortress Basement":            "Beneath the Fortress",
		"Fortress Main":                "Eastern Vault Fortress",
		"Fortress East":                "Fortress East Shortcut",
		"Fortress Reliquary":           "Fortress Grave Path",
		"Fortress Courtyard":           "Fortress Courtyard",
		"Dusty":                        "Fortress Leaf Piles",
		"Fortress Arena":               "Fortress Arena",
		"Mountain":                     "Lower Mountain",
		"Mountaintop":                  "Top of the Mountain",
		"Darkwoods Tunnel":             "Quarry Entryway",
		"Quarry Redux":                 "Quarry",
		"Monastery":                    "Monastery",
		"ziggurat2020_0":               "Rooted Ziggurat Entrance",
		"ziggurat2020_1":               "Rooted Ziggurat Upper",
		"ziggurat2020_2":               "Rooted Ziggurat Tower",
		"ziggurat2020_3":               "Rooted Ziggurat Lower",
		"ziggurat2020_FTRoom":          "Rooted Ziggurat Teleporter",
		"Swamp Redux 2":                "Swamp",
		"Cathedral Redux":              "Cathedral",
		"Cathedral Arena":              "Cathedral Gauntlet",
		"RelicVoid":                    "Hero's Grave",
		"g_elements":                   "Glyph Tower",
		"Spirit Arena":                 "The Heir",
		"Purgatory":                    "Purgatory",
		"Posterity":                    "Posterity",
	}
	allDoors = map[string][]string{
		"Overworld":                  {"Spawn to Far Shore", "Town to Far Shore", "Stairs from Overworld to Mountain", "Temple Rafters Entrance", "Temple Door Entrance", "Stick House Entrance", "Overworld to Fortress", "Ruined Shop Entrance", "Hourglass Cave Entrance", "Old House Door Entrance", "Fountain HC Door Entrance", "Cube Cave Entrance", "Atoll Upper Entrance", "Atoll Lower Entrance", "Special Shop Entrance", "Old House Waterfall Entrance", "Maze Cave Entrance", "Ruined Passage Door Entrance", "Ruined Passage Not-Door Entrance", "Changing Room Entrance", "Swamp Upper Entrance", "Swamp Lower Entrance", "Dark Tomb Main Entrance", "Patrol Cave Entrance", "Caustic Light Cave Entrance", "Well Ladder Entrance", "West Garden Entrance near Belltower", "Windmill Entrance", "Entrance to Furnace under Windmill", "Secret Gathering Place Entrance", "Entrance to Furnace near West Garden", "West Garden Entrance from Furnace", "West Garden Laurels Entrance", "Overworld to Quarry Connector", "Overworld to Forest Belltower", "Entrance to Furnace from Beach", "Southeast HC Door Entrance", "Entrance to Furnace from Well Rail", "Entrance to Well from Well Rail"},
		"West Furnace":               {"Furnace Exit towards Well", "Furnace Exit towards West Garden", "Furnace Exit under Windmill", "Furnace Exit to Beach", "Furnace Exit to Dark Tomb"},
		"Cube Cave":                  {"Cube Cave Exit"},
		"Stick House":                {"Stick House Exit"},
		"Windmill":                   {"Windmill Exit", "Windmill Shop"},
		"Southeast Cross Door":       {"Southeast HC Room Exit"},
		"Caustic Light Cave":         {"Caustic Light Cave Exit"},
		"Ruined Passage":             {"Ruined Passage Door Exit", "Ruined Passage Not-Door Exit"},
		"Patrol Cave":                {"Guard Patrol Cave Exit"},
		"Secret Gathering Place":     {"Secret Gathering Place Exit"},
		"Fountain Cross Door":        {"Fountain HC Room Exit"},
		"Hourglass Cave":             {"Hourglass Cave Exit"},
		"Maze Cave":                  {"Maze Cave Exit"},
		"Ruined Shop":                {"Ruined Shop Exit"},
		"Changing Room":              {"Changing Room Exit"},
		"Special Shop":               {"Special Shop Exit"},
		"Old House":                  {"Old House Door Exit", "Old House Waterfall Exit", "Old House to Glyph Tower"},
		"Far Shore":                  {"Far Shore to Quarry", "Far Shore to Ziggurat", "Far Shore to Atoll", "Far Shore to Spawn", "Far Shore to Town", "Far Shore to Library", "Far Shore to Fortress", "Far Shore to Heir", "Far Shore to East Forest", "Far Shore to West Garden"},
		"Sealed Temple":              {"Temple Door Exit", "Temple Rafters Exit"},
		"Shop":                       {"Shop Portal"},
		"Forest Belltower":           {"Forest Belltower to Forest", "Forest Belltower to Overworld", "Forest Belltower to Guard Captain Room", "Forest Belltower to Fortress"},
		"East Forest":                {"Forest to Far Shore", "Forest to Belltower", "Forest Guard House 1 Gate Entrance", "Forest Guard House 1 Lower Entrance", "Forest Guard House 2 Upper Entrance", "Forest Guard House 2 Lower Entrance", "Forest Grave Path Lower Entrance", "Forest Grave Path Upper Entrance", "Forest Dance Fox Outside Doorway"},
		"Forest Grave Path":          {"East Forest Hero's Grave", "Forest Grave Path Upper Exit", "Forest Grave Path Lower Exit"},
		"Guardhouse 2":               {"Guard House 2 Upper Exit", "Guard House 2 Lower Exit"},
		"Guardhouse 1":               {"Guard House 1 Dance Fox Exit", "Guard House 1 Lower Exit", "Guard House 1 to Guard Captain Room", "Guard House 1 Upper Forest Exit"},
		"Forest Boss Room":           {"Guard Captain Room Gate Exit", "Guard Captain Room Non-Gate Exit"},
		"Beneath the Well":           {"Well to Well Boss", "Well Exit towards Furnace", "Well Ladder Exit"},
		"Dark Tomb Checkpoint":       {"Well Boss to Well", "Checkpoint to Dark Tomb"},
		"Dark Tomb":                  {"Dark Tomb to Overworld", "Dark Tomb to Checkpoint", "Dark Tomb to Furnace"},
		"West Garden":                {"West Garden Shop", "West Garden to Magic Dagger House", "West Garden to Far Shore", "West Garden Hero's Grave", "West Garden Laurels Exit", "West Garden Exit near Hero's Grave", "West Garden Exit after Boss"},
		"West Garden House":          {"Magic Dagger House Exit"},
		"Ruined Atoll":               {"Atoll Upper Exit", "Atoll Lower Exit", "Frog Stairs Mouth Entrance", "Frog Stairs Eye Entrance", "Atoll Shop", "Atoll Statue Teleporter", "Atoll to Far Shore"},
		"Frog Stairway":              {"Frog Stairs Eye Exit", "Frog Stairs Mouth Exit", "Frog Stairs to Frog's Domain's Entrance", "Frog Stairs to Frog's Domain's Exit"},
		"Frog's Domain":              {"Frog's Domain Orb Exit", "Frog's Domain Ladder Exit"},
		"Library Exterior":           {"Library Exterior Tree", "Library Exterior Ladder"},
		"Library Hall":               {"Library Hall Bookshelf Exit", "Library Hero's Grave", "Library Hall to Rotunda"},
		"Library Rotunda":            {"Library Rotunda Upper Exit", "Library Rotunda Lower Exit"},
		"Library Lab":                {"Library Lab to Rotunda", "Library to Far Shore", "Library Lab to Librarian Arena"},
		"Librarian":                  {"Librarian Arena Exit"},
		"Beneath the Fortress":       {"Beneath the Earth to Fortress Courtyard", "Beneath the Earth to Fortress Interior"},
		"Eastern Vault Fortress":     {"Fortress Interior Shop", "Fortress Interior to East Fortress Upper", "Fortress Interior to East Fortress Lower", "Fortress Interior to Beneath the Earth", "Fortress Interior to Siege Engine Arena", "Fortress Interior Main Exit"},
		"Fortress East Shortcut":     {"East Fortress to Interior Lower", "East Fortress to Interior Upper", "East Fortress to Courtyard"},
		"Fortress Grave Path":        {"Fortress Grave Path Dusty Entrance", "Fortress Hero's Grave", "Fortress Grave Path Upper Exit", "Fortress Grave Path Lower Exit"},
		"Fortress Courtyard":         {"Fortress Courtyard to Fortress Grave Path Lower", "Fortress Courtyard to Fortress Grave Path Upper", "Fortress Courtyard to Overworld", "Fortress Courtyard to Fortress Interior", "Fortress Courtyard to East Fortress", "Fortress Courtyard to Beneath the Earth", "Fortress Courtyard Shop", "Fortress Courtyard to Forest Belltower"},
		"Fortress Leaf Piles":        {"Dusty Exit"},
		"Fortress Arena":             {"Fortress to Far Shore", "Siege Engine Arena to Fortress"},
		"Lower Mountain":             {"Mountain to Quarry", "Stairs to Top of the Mountain", "Mountain to Overworld"},
		"Top of the Mountain":        {"Top of the Mountain Exit"},
		"Quarry Entryway":            {"Quarry Connector to Quarry", "Quarry Connector to Overworld"},
		"Quarry":                     {"Quarry to Far Shore", "Quarry to Ziggurat", "Quarry to Monastery Front", "Quarry to Monastery Back", "Quarry to Overworld Exit", "Quarry Shop", "Quarry to Mountain"},
		"Monastery":                  {"Monastery Hero's Grave", "Monastery Rear Exit", "Monastery Front Exit"},
		"Rooted Ziggurat Entrance":   {"Ziggurat Entry Hallway to Quarry", "Ziggurat Entry Hallway to Ziggurat Upper"},
		"Rooted Ziggurat Upper":      {"Ziggurat Upper to Ziggurat Entry Hallway", "Ziggurat Upper to Ziggurat Tower"},
		"Rooted Ziggurat Tower":      {"Ziggurat Tower to Ziggurat Upper", "Ziggurat Tower to Ziggurat Lower"},
		"Rooted Ziggurat Lower":      {"Ziggurat Lower to Ziggurat Tower", "Ziggurat Portal Room Entrance"},
		"Rooted Ziggurat Teleporter": {"Ziggurat to Far Shore", "Ziggurat Portal Room Exit"},
		"Swamp":                      {"Swamp Shop", "Swamp Upper Exit", "Swamp Lower Exit", "Swamp to Gauntlet", "Swamp Hero's Grave", "Swamp to Cathedral Secret Legend Room Entrance", "Swamp to Cathedral Main Entrance"},
		"Cathedral":                  {"Cathedral Secret Legend Room Exit", "Cathedral Main Exit", "Cathedral Elevator"},
		"Cathedral Gauntlet":         {"Gauntlet Shop", "Gauntlet Elevator", "Gauntlet to Swamp"},
		"Hero's Grave":               {"Hero's Grave to Swamp", "Hero's Grave to Fortress", "Hero's Grave to Library", "Hero's Grave to East Forest", "Hero's Grave to West Garden", "Hero's Grave to Monastery"},
		"Glyph Tower":                {"Glyph Tower Exit"},
		"The Heir":                   {"Heir Arena Exit"},
		"Purgatory":                  {"Purgatory Bottom Exit", "Purgatory Top Exit"},
	}
	doorRegions = map[string]string{
		"Temple Door Exit":                                "Sealed Temple",
		"Temple Rafters Exit":                             "Sealed Temple",
		"Ziggurat Entry Hallway to Quarry":                "Rooted Ziggurat Entrance",
		"Ziggurat Entry Hallway to Ziggurat Upper":        "Rooted Ziggurat Entrance",
		"Purgatory Bottom Exit":                           "Purgatory",
		"Purgatory Top Exit":                              "Purgatory",
		"Caustic Light Cave Exit":                         "Caustic Light Cave",
		"West Garden Shop":                                "West Garden",
		"West Garden to Magic Dagger House":               "West Garden",
		"West Garden to Far Shore":                        "West Garden",
		"West Garden Hero's Grave":                        "West Garden",
		"West Garden Laurels Exit":                        "West Garden",
		"West Garden Exit near Hero's Grave":              "West Garden",
		"West Garden Exit after Boss":                     "West Garden",
		"Frog's Domain Orb Exit":                          "Frog's Domain",
		"Frog's Domain Ladder Exit":                       "Frog's Domain",
		"Library Hall Bookshelf Exit":                     "Library Hall",
		"Library Hero's Grave":                            "Library Hall",
		"Library Hall to Rotunda":                         "Library Hall",
		"Maze Cave Exit":                                  "Maze Cave",
		"Cube Cave Exit":                                  "Cube Cave",
		"Special Shop Exit":                               "Special Shop",
		"Furnace Exit towards Well":                       "West Furnace",
		"Furnace Exit towards West Garden":                "West Furnace",
		"Furnace Exit under Windmill":                     "West Furnace",
		"Furnace Exit to Beach":                           "West Furnace",
		"Furnace Exit to Dark Tomb":                       "West Furnace",
		"Well to Well Boss":                               "Beneath the Well",
		"Well Exit towards Furnace":                       "Beneath the Well",
		"Well Ladder Exit":                                "Beneath the Well",
		"Fortress to Far Shore":                           "Fortress Arena",
		"Siege Engine Arena to Fortress":                  "Fortress Arena",
		"Old House Door Exit":                             "Old House",
		"Old House Waterfall Exit":                        "Old House",
		"Old House to Glyph Tower":                        "Old House",
		"Southeast HC Room Exit":                          "Southeast Cross Door",
		"Library Rotunda Upper Exit":                      "Library Rotunda",
		"Library Rotunda Lower Exit":                      "Library Rotunda",
		"Mountain to Quarry":                              "Lower Mountain",
		"Stairs to Top of the Mountain":                   "Lower Mountain",
		"Mountain to Overworld":                           "Lower Mountain",
		"Stick House Exit":                                "Stick House",
		"Magic Dagger House Exit":                         "West Garden House",
		"Fortress Grave Path Dusty Entrance":              "Fortress Grave Path",
		"Fortress Hero's Grave":                           "Fortress Grave Path",
		"Fortress Grave Path Upper Exit":                  "Fortress Grave Path",
		"Fortress Grave Path Lower Exit":                  "Fortress Grave Path",
		"Shop Portal":                                     "Shop",
		"East Fortress to Interior Lower":                 "Fortress East Shortcut",
		"East Fortress to Interior Upper":                 "Fortress East Shortcut",
		"East Fortress to Courtyard":                      "Fortress East Shortcut",
		"Top of the Mountain Exit":                        "Top of the Mountain",
		"Swamp Shop":                                      "Swamp",
		"Swamp Upper Exit":                                "Swamp",
		"Swamp Lower Exit":                                "Swamp",
		"Swamp to Gauntlet":                               "Swamp",
		"Swamp Hero's Grave":                              "Swamp",
		"Swamp to Cathedral Secret Legend Room Entrance":  "Swamp",
		"Swamp to Cathedral Main Entrance":                "Swamp",
		"Fortress Interior Shop":                          "Eastern Vault Fortress",
		"Fortress Interior to East Fortress Upper":        "Eastern Vault Fortress",
		"Fortress Interior to East Fortress Lower":        "Eastern Vault Fortress",
		"Fortress Interior to Beneath the Earth":          "Eastern Vault Fortress",
		"Fortress Interior to Siege Engine Arena":         "Eastern Vault Fortress",
		"Fortress Interior Main Exit":                     "Eastern Vault Fortress",
		"Quarry to Far Shore":                             "Quarry",
		"Quarry to Ziggurat":                              "Quarry",
		"Quarry to Monastery Front":                       "Quarry",
		"Quarry to Monastery Back":                        "Quarry",
		"Quarry to Overworld Exit":                        "Quarry",
		"Quarry Shop":                                     "Quarry",
		"Quarry to Mountain":                              "Quarry",
		"Heir Arena Exit":                                 "The Heir",
		"Forest Belltower to Forest":                      "Forest Belltower",
		"Forest Belltower to Overworld":                   "Forest Belltower",
		"Forest Belltower to Guard Captain Room":          "Forest Belltower",
		"Forest Belltower to Fortress":                    "Forest Belltower",
		"Guard House 2 Upper Exit":                        "Guardhouse 2",
		"Guard House 2 Lower Exit":                        "Guardhouse 2",
		"Monastery Hero's Grave":                          "Monastery",
		"Monastery Rear Exit":                             "Monastery",
		"Monastery Front Exit":                            "Monastery",
		"Glyph Tower Exit":                                "Glyph Tower",
		"Far Shore to Quarry":                             "Far Shore",
		"Far Shore to Ziggurat":                           "Far Shore",
		"Far Shore to Atoll":                              "Far Shore",
		"Far Shore to Spawn":                              "Far Shore",
		"Far Shore to Town":                               "Far Shore",
		"Far Shore to Library":                            "Far Shore",
		"Far Shore to Fortress":                           "Far Shore",
		"Far Shore to Heir":                               "Far Shore",
		"Far Shore to East Forest":                        "Far Shore",
		"Far Shore to West Garden":                        "Far Shore",
		"Gauntlet Shop":                                   "Cathedral Gauntlet",
		"Gauntlet Elevator":                               "Cathedral Gauntlet",
		"Gauntlet to Swamp":                               "Cathedral Gauntlet",
		"Hero's Grave to Swamp":                           "Hero's Grave",
		"Hero's Grave to Fortress":                        "Hero's Grave",
		"Hero's Grave to Library":                         "Hero's Grave",
		"Hero's Grave to East Forest":                     "Hero's Grave",
		"Hero's Grave to West Garden":                     "Hero's Grave",
		"Hero's Grave to Monastery":                       "Hero's Grave",
		"Ziggurat Upper to Ziggurat Entry Hallway":        "Rooted Ziggurat Upper",
		"Ziggurat Upper to Ziggurat Tower":                "Rooted Ziggurat Upper",
		"Windmill Exit":                                   "Windmill",
		"Windmill Shop":                                   "Windmill",
		"Secret Gathering Place Exit":                     "Secret Gathering Place",
		"East Forest Hero's Grave":                        "Forest Grave Path",
		"Forest Grave Path Upper Exit":                    "Forest Grave Path",
		"Forest Grave Path Lower Exit":                    "Forest Grave Path",
		"Guard Captain Room Gate Exit":                    "Forest Boss Room",
		"Guard Captain Room Non-Gate Exit":                "Forest Boss Room",
		"Dusty Exit":                                      "Fortress Leaf Piles",
		"Cathedral Secret Legend Room Exit":               "Cathedral",
		"Cathedral Main Exit":                             "Cathedral",
		"Cathedral Elevator":                              "Cathedral",
		"Spawn to Far Shore":                              "Overworld",
		"Town to Far Shore":                               "Overworld",
		"Stairs from Overworld to Mountain":               "Overworld",
		"Temple Rafters Entrance":                         "Overworld",
		"Temple Door Entrance":                            "Overworld",
		"Stick House Entrance":                            "Overworld",
		"Overworld to Fortress":                           "Overworld",
		"Ruined Shop Entrance":                            "Overworld",
		"Hourglass Cave Entrance":                         "Overworld",
		"Old House Door Entrance":                         "Overworld",
		"Fountain HC Door Entrance":                       "Overworld",
		"Cube Cave Entrance":                              "Overworld",
		"Atoll Upper Entrance":                            "Overworld",
		"Atoll Lower Entrance":                            "Overworld",
		"Special Shop Entrance":                           "Overworld",
		"Old House Waterfall Entrance":                    "Overworld",
		"Maze Cave Entrance":                              "Overworld",
		"Ruined Passage Door Entrance":                    "Overworld",
		"Ruined Passage Not-Door Entrance":                "Overworld",
		"Changing Room Entrance":                          "Overworld",
		"Swamp Upper Entrance":                            "Overworld",
		"Swamp Lower Entrance":                            "Overworld",
		"Dark Tomb Main Entrance":                         "Overworld",
		"Patrol Cave Entrance":                            "Overworld",
		"Caustic Light Cave Entrance":                     "Overworld",
		"Well Ladder Entrance":                            "Overworld",
		"West Garden Entrance near Belltower":             "Overworld",
		"Windmill Entrance":                               "Overworld",
		"Entrance to Furnace under Windmill":              "Overworld",
		"Secret Gathering Place Entrance":                 "Overworld",
		"Entrance to Furnace near West Garden":            "Overworld",
		"West Garden Entrance from Furnace":               "Overworld",
		"West Garden Laurels Entrance":                    "Overworld",
		"Overworld to Quarry Connector":                   "Overworld",
		"Overworld to Forest Belltower":                   "Overworld",
		"Entrance to Furnace from Beach":                  "Overworld",
		"Southeast HC Door Entrance":                      "Overworld",
		"Entrance to Furnace from Well Rail":              "Overworld",
		"Entrance to Well from Well Rail":                 "Overworld",
		"Fountain HC Room Exit":                           "Fountain Cross Door",
		"Hourglass Cave Exit":                             "Hourglass Cave",
		"Changing Room Exit":                              "Changing Room",
		"Forest to Far Shore":                             "East Forest",
		"Forest to Belltower":                             "East Forest",
		"Forest Guard House 1 Gate Entrance":              "East Forest",
		"Forest Guard House 1 Lower Entrance":             "East Forest",
		"Forest Guard House 2 Upper Entrance":             "East Forest",
		"Forest Guard House 2 Lower Entrance":             "East Forest",
		"Forest Grave Path Lower Entrance":                "East Forest",
		"Forest Grave Path Upper Entrance":                "East Forest",
		"Forest Dance Fox Outside Doorway":                "East Forest",
		"Atoll Upper Exit":                                "Ruined Atoll",
		"Atoll Lower Exit":                                "Ruined Atoll",
		"Frog Stairs Mouth Entrance":                      "Ruined Atoll",
		"Frog Stairs Eye Entrance":                        "Ruined Atoll",
		"Atoll Shop":                                      "Ruined Atoll",
		"Atoll Statue Teleporter":                         "Ruined Atoll",
		"Atoll to Far Shore":                              "Ruined Atoll",
		"Library Lab to Rotunda":                          "Library Lab",
		"Library to Far Shore":                            "Library Lab",
		"Library Lab to Librarian Arena":                  "Library Lab",
		"Fortress Courtyard to Fortress Grave Path Lower": "Fortress Courtyard",
		"Fortress Courtyard to Fortress Grave Path Upper": "Fortress Courtyard",
		"Fortress Courtyard to Overworld":                 "Fortress Courtyard",
		"Fortress Courtyard to Fortress Interior":         "Fortress Courtyard",
		"Fortress Courtyard to East Fortress":             "Fortress Courtyard",
		"Fortress Courtyard to Beneath the Earth":         "Fortress Courtyard",
		"Fortress Courtyard Shop":                         "Fortress Courtyard",
		"Fortress Courtyard to Forest Belltower":          "Fortress Courtyard",
		"Ruined Passage Door Exit":                        "Ruined Passage",
		"Ruined Passage Not-Door Exit":                    "Ruined Passage",
		"Ziggurat Lower to Ziggurat Tower":                "Rooted Ziggurat Lower",
		"Ziggurat Portal Room Entrance":                   "Rooted Ziggurat Lower",
		"Librarian Arena Exit":                            "Librarian",
		"Beneath the Earth to Fortress Courtyard":         "Beneath the Fortress",
		"Beneath the Earth to Fortress Interior":          "Beneath the Fortress",
		"Guard House 1 Dance Fox Exit":                    "Guardhouse 1",
		"Guard House 1 Lower Exit":                        "Guardhouse 1",
		"Guard House 1 to Guard Captain Room":             "Guardhouse 1",
		"Guard House 1 Upper Forest Exit":                 "Guardhouse 1",
		"Well Boss to Well":                               "Dark Tomb Checkpoint",
		"Checkpoint to Dark Tomb":                         "Dark Tomb Checkpoint",
		"Frog Stairs Eye Exit":                            "Frog Stairway",
		"Frog Stairs Mouth Exit":                          "Frog Stairway",
		"Frog Stairs to Frog's Domain's Entrance":         "Frog Stairway",
		"Frog Stairs to Frog's Domain's Exit":             "Frog Stairway",
		"Library Exterior Tree":                           "Library Exterior",
		"Library Exterior Ladder":                         "Library Exterior",
		"Ziggurat Tower to Ziggurat Upper":                "Rooted Ziggurat Tower",
		"Ziggurat Tower to Ziggurat Lower":                "Rooted Ziggurat Tower",
		"Ziggurat to Far Shore":                           "Rooted Ziggurat Teleporter",
		"Ziggurat Portal Room Exit":                       "Rooted Ziggurat Teleporter",
		"Guard Patrol Cave Exit":                          "Patrol Cave",
		"Dark Tomb to Overworld":                          "Dark Tomb",
		"Dark Tomb to Checkpoint":                         "Dark Tomb",
		"Dark Tomb to Furnace":                            "Dark Tomb",
		"Quarry Connector to Quarry":                      "Quarry Entryway",
		"Quarry Connector to Overworld":                   "Quarry Entryway",
		"Ruined Shop Exit":                                "Ruined Shop",
	}
)

func TranslateScene(scene string) (string, error) {
	name, ok := sceneNames[scene]
	if !ok {
		return "", fmt.Errorf("unrecognized scene: %s", scene)
	}
	return name, nil
}

func GetDoorArea(door string) (string, error) {
	for area, doors := range allDoors {
		for _, current := range doors {
			if door == current {
				return area, nil
			}
		}
	}
	return "", fmt.Errorf("unrecognized door: %s", door)
}

func GetAreaDoors(area string) ([]string, error) {
	doors, ok := allDoors[area]
	if !ok {
		return nil, fmt.Errorf("unrecognized area: %s", area)
	}
	return doors, nil
}
